services:
  - type: web
    name: project-api
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: Dockerfile
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: "3000"
